#!/usr/bin/env python

import warnings
warnings.filterwarnings("ignore")
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import numpy as np
from scipy.ndimage import imread
from canvas import canvasUI
from keras.models import load_model

model = load_model("utils/model.hdf5")

ch = 'y'
while ch=='y':
    canvasUI()
    img = imread('utils/temp.jpg', flatten=True)
    img = (255.0 - img)/255.0
    img = img.reshape((1,28,28,1))
    if (img == np.zeros((1,28,28,1))).all():
        print "NO INPUT GIVEN!"
    else:
        AL = model.predict(img, batch_size=1)
        pred = AL.argmax(axis=1)
        conf = 100 * AL[0][pred].squeeze()/np.sum(AL)
        print "Prediction:", pred[0],'\tConfidence:',round(conf,5),'%\n'
    ch = raw_input("Want to try again?([y]/n):").strip().lower()
    if ch!='y':
        print "Aborting..."
        break
